/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include "tlc.h"
#include "led_config.h"

ISR(TIMER1_COMPA_vect) {
    TLC_BLANK_PORT |= 1<<TLC_BLANK;// write blank HIGH to reset the 4096 counter in the TLC
    TLC_XLAT_PORT |= 1<<TLC_XLAT;// write XLAT HIGH to latch in data from the last data stream
    TLC_XLAT_PORT &= ~(1<<TLC_XLAT);  //XLAT can go low now
    TLC_BLANK_PORT &= ~(1<<TLC_BLANK);//Blank goes LOW to start the next cycle
    //SPI_0_disable();//end the SPI so we can write to the clock pin
    //TLC_SCLK_PORT |= 1<<TLC_SCLK;// SPI Clock pin to give it the extra count
    //TLC_SCLK_PORT &= ~(1<<TLC_SCLK_PORT);// The data sheet says you need this for some reason?
    //SPI_0_enable();
    // TODO: optimize transfer size
    SPI_0_write_block(tlc_spi_transferbyte, sizeof(tlc_spi_transferbyte[0]) * TLC_SPI_TRANSFER_SIZE);
    //while(SPI_0_status_busy());
}
